[package]
name = "ente-photos-frb"
edition.workspace = true

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
ente-assets.workspace = true
ente-cast.workspace = true
ente-core.workspace = true
ente-frb-lib = { workspace = true, features = ["contacts", "legacy"] }
ente-frb-log.workspace = true
ente-image.workspace = true
ente-location.workspace = true
ente-ml = { workspace = true, features = ["usearch"] }
ente-photos.workspace = true
flutter_rust_bridge.workspace = true
log.workspace = true

[lints]
workspace = true

[features]
default = []
flutter = []
