[package]
name = "ente_photos_rust"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
ente-image.workspace = true
ente-photos.workspace = true
flutter_rust_bridge.workspace = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }

[features]
default = []
flutter = []
