[package]
name = "ente-photos-frb"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
ente-cast.workspace = true
ente-core.workspace = true
ente-frb-lib = { workspace = true, features = ["contacts"] }
ente-frb-log.workspace = true
ente-image.workspace = true
ente-location.workspace = true
ente-ml = { workspace = true, features = ["usearch"] }
ente-photos.workspace = true
flutter_rust_bridge.workspace = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }

[features]
default = []
flutter = []
