package api

import "github.com/gin-gonic/gin"

func Register(privateAPI, publicAPI gin.IRoutes, handlers *Handlers) {
	privateAPI.POST("/space/entity-key", handlers.CreateSpaceEntityKey)
	privateAPI.POST("/space/entity-key/ensure", handlers.EnsureSpaceEntityKey)
	privateAPI.GET("/space/entity-key", handlers.GetSpaceEntityKey)
	privateAPI.GET("/space", handlers.ListSpaces)
	privateAPI.POST("/space", handlers.CreateSpace)
	privateAPI.POST("/space/profile", handlers.UpdateSpaceProfile)
	privateAPI.PUT("/space/:spaceID/slug", handlers.UpdateSpaceSlug)
	privateAPI.PATCH("/space/:spaceID/slug", handlers.UpdateSpaceSlug)
	privateAPI.POST("/space/uploads/presign", handlers.PresignUpload)
	privateAPI.GET("/space/unread", handlers.GetUnreadStatus)
	privateAPI.POST("/space/posts", handlers.CreatePost)
	privateAPI.GET("/space/feed", handlers.ListFeed)
	privateAPI.POST("/space/posts/:postID/caption", handlers.UpdatePostCaption)
	privateAPI.PATCH("/space/posts/:postID/caption", handlers.UpdatePostCaption)
	privateAPI.POST("/space/posts/:postID/like", handlers.TogglePostLike)
	privateAPI.POST("/space/posts/:postID/reply", handlers.ReplyToPost)
	privateAPI.DELETE("/space/posts/:postID", handlers.DeletePost)
	privateAPI.GET("/space/notifications", handlers.ListNotifications)
	privateAPI.POST("/space/notifications/read", handlers.MarkNotificationsRead)
	privateAPI.GET("/space/messages", handlers.ListMessages)
	privateAPI.POST("/space/messages/likes/read", handlers.MarkMessageLikesRead)
	privateAPI.POST("/space/messages/read", handlers.MarkMessageThreadRead)
	privateAPI.GET("/space/messages/:spaceID", handlers.ListMessageThread)
	privateAPI.POST("/space/messages/:spaceID", handlers.CreateMessage)
	privateAPI.POST("/space/message/:messageID/like", handlers.ToggleMessageLike)
	privateAPI.DELETE("/space/message/:messageID", handlers.DeleteMessage)
	privateAPI.POST("/space/friends/add", handlers.AddFriend)
	privateAPI.POST("/space/friends/unfriend", handlers.Unfriend)
	privateAPI.GET("/space/friends", handlers.ListSpaceFriends)
	privateAPI.GET("/space/friends/relationship", handlers.FriendRelationship)
	privateAPI.POST("/space/friends/shares/refresh", handlers.RefreshFriendShares)
	privateAPI.GET("/space/friends/shares", handlers.ListFriendShares)
	privateAPI.POST("/space/rotate", handlers.RotateSpaceKey)
	privateAPI.GET("/space/links/:spaceID", handlers.GetSpaceLink)
	privateAPI.POST("/space/links", handlers.CreateSpaceLink)
	privateAPI.POST("/space/links/rotate", handlers.RotateSpaceLink)
	privateAPI.DELETE("/space/links/:spaceID", handlers.DeleteSpaceLink)

	publicAPI.GET("/space/profile", handlers.GetSpaceProfile)
	publicAPI.GET("/space/assets/redirect", handlers.AssetRedirect)
	publicAPI.GET("/space/posts", handlers.ListPosts)
	publicAPI.GET("/space/posts/:postID", handlers.GetPost)
	publicAPI.GET("/space/posts/:postID/likes", handlers.ListPostLikers)
	publicAPI.GET("/space/versions", handlers.ListSpaceKeyVersions)
	publicAPI.GET("/space/public/by-slug/:spaceSlug", handlers.LookupSpaceBySlug)
	publicAPI.GET("/space/public/slug-availability/:spaceSlug", handlers.SpaceSlugAvailability)
	publicAPI.POST("/space/links/session", handlers.SpaceLinkLogin)
	publicAPI.POST("/space/sessions/bootstrap", handlers.BootstrapBrowserSession)
	publicAPI.DELETE("/space/sessions/current", handlers.DeleteBrowserSession)
}

func RegisterTokenSessionRoutes(privateAPI gin.IRoutes, handlers *Handlers) {
	privateAPI.POST("/space/sessions", handlers.CreateBrowserSession)
}
