[package]
name = "ente_photos_napi"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
# usearch requires a newer GCC than napi-cli provides.
ente-assets.workspace = true
ente-photos.workspace = true
napi = { version = "3", default-features = false, features = ["napi10", "tokio_rt"] }
napi-derive = "3"
ort = { workspace = true, features = ["load-dynamic"] }

[build-dependencies]
napi-build = "2"
