[package]
name = "ente-legacy"
edition.workspace = true

[dependencies]
ente-accounts.workspace = true
ente-core.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
uuid = { workspace = true, features = ["v4", "js"] }

[lints]
workspace = true
