import { assertionFailed } from "ente-base/assert";

/**
 * The version of the face indexing pipeline implemented by the current client.
 */
export const faceIndexingVersion = 1;

/**
 * The faces in a file (and an embedding for each of them).
 *
 * This interface describes the format of face related data (aka "face index")
 * for a file. This is the common subset that is present in both the fields that
 * are persisted on remote ({@link RemoteFaceIndex}) and locally
 * ({@link LocalFaceIndex}).
 *
 * - Face detections and embeddings (collectively called as the face index) are
 *   generated by the current client when uploading a file, or when noticing a
 *   file which doesn't yet have a face index. They are then uploaded (E2EE) to
 *   remote, and the relevant bits also saved locally in the ML DB for
 *   subsequent lookup or clustering.
 *
 * - This face index is then fetched by subsequent clients to avoid them having
 *   to reindex (indexing faces is a costly operation, esp. for mobile clients).
 *
 * In both these scenarios (whether generated locally or fetched from remote),
 * we end up with an some data described by this {@link FaceIndex} interface. We
 * modify it slightly, adding envelopes, when saving them locally or uploading
 * them to remote - those variations are described by the {@link LocalFaceIndex}
 * and {@link RemoteFaceIndex} types respectively.
 */
export interface FaceIndex {
    /**
     * The width (in px) of the image (file).
     *
     * Having the image dimensions here is useful since the coordinates inside
     * the {@link Face}s are all normalized (0 to 1) to the width and height of
     * the image.
     */
    width: number;
    /**
     * The height (in px) of the image (file).
     */
    height: number;
    /**
     * The list of faces (and their embeddings) detected in the file.
     *
     * Each of the items is a {@link Face}, containing the result of a face
     * detection, and an embedding for that detected face.
     */
    faces: Face[];
}

export type RemoteFaceIndex = FaceIndex & {
    /**
     * An integral version number of the indexing algorithm / pipeline.
     *
     * [Note: Embedding versions]
     *
     * Embeddings have an associated version so it is possible for us to make
     * backward compatible updates to the indexing process on newer clients.
     *
     * Clients agree out of band what a particular version means, and guarantee
     * that an embedding with a particular version will be the same (to epsilon
     * cosine similarity) irrespective of the client that indexed the file.
     *
     * If we bump the version of same model (say when indexing on a newer
     * client), we will do it in a manner that older client will be able to
     * consume the response.  The schema should not change in non-additive
     * manners. For example, say if we improve blur detection, older client
     * should just consume embeddings with a newer version and not try to index
     * the file again locally.
     *
     * When fetching from remote, if we get an embedding with version that is
     * older than the version the client supports, then the client should ignore
     * it. This way, the file will get reindexed locally and an embedding with a
     * newer version will also get saved to remote.
     *
     * In the case where the changes are not backward compatible and can only be
     * consumed by clients by making code changes, then we will introduce a new
     * subtype (top level key) in the derived data.
     */
    version: number;
    /**
     * The UA for the client which generated this embedding.
     */
    client: string;
    /**
     * Bitmask describing the runtime that generated this index. An absent
     * value on legacy remote data is parsed as zero.
     */
    flags: number;
};

export type LocalFaceIndex = FaceIndex & {
    /**
     * The ID of the {@link EnteFile} whose index this is.
     *
     * This is used as the primary key when storing the index locally (An
     * {@link EnteFile} is guaranteed to have its fileID be unique in the
     * namespace of the user. Even if someone shares a file with the user the
     * user will get a file entry with a fileID unique to them).
     */
    fileID: number;
};

/**
 * A face detected in a file, and an embedding for this detected face.
 *
 * During face indexing, we first detect all the faces in a particular file.
 * Then for each such detected region, we compute an embedding of that part of
 * the file. Together, this detection region and the emedding travel together in
 * this {@link Face} interface.
 */
export interface Face {
    /**
     * A unique identifier for the face.
     *
     * This ID is guaranteed to be unique for all the faces detected in all the
     * files for the user. In particular, each file can have multiple faces but
     * they all will get their own unique {@link faceID}.
     *
     * This ID is also meant to be stable across reindexing. That is, if the
     * same algorithm and hyperparameters are used to reindex the file, then it
     * should result in the same face IDs. This allows us leeway in letting
     * unnecessary reindexing happen in rare cases without invalidating the
     * clusters that rely on the presence of the given face ID.
     *
     * Finally, this face ID is not completely opaque. It consists of underscore
     * separated components, the first of which is the ID of the
     * {@link EnteFile} to which this face belongs. Client code can rely on this
     * structure and can parse it if needed using {@link fileIDFromFaceID}.
     */
    faceID: string;
    /**
     * The face detection. Describes the region within the image that was
     * detected to be a face, and a set of landmarks (e.g. "eyes") of the
     * detection.
     *
     * All coordinates are relative to and normalized by the image's dimension,
     * i.e. they have been normalized to lie between 0 and 1, with 0 being the
     * left (or top) and 1 being the width (or height) of the image.
     */
    detection: {
        /**
         * The region within the image that contains the face.
         *
         * All coordinates and sizes are between 0 and 1, normalized by the
         * dimensions of the image.
         * */
        box: Box;
        /**
         * Face "landmarks", e.g. eyes.
         *
         * The exact landmarks and their order depends on the face detection
         * algorithm being used.
         *
         * The coordinatesare between 0 and 1, normalized by the dimensions of
         * the image.
         */
        landmarks: Point[];
    };
    /**
     * An correctness probability (0 to 1) that the face detection algorithm
     * gave to the detection. Higher values are better.
     */
    score: number;
    /**
     * The computed blur for the detected face.
     *
     * The exact semantics and range for these (floating point) values depend on
     * the face indexing algorithm / pipeline version being used.
     * */
    blur: number;
    /**
     * An embedding for the face.
     *
     * This is an opaque numeric (signed floating point) vector whose semantics
     * and length depend on the version of the face indexing algorithm /
     * pipeline that we are using. However, within a set of embeddings with the
     * same version, the property is that two such embedding vectors will be
     * "cosine similar" to each other if they are both faces of the same person.
     */
    embedding: number[];
}

/** The x and y coordinates of a point. */
export interface Point {
    x: number;
    y: number;
}

/** The dimensions of something, say an image. */
export interface Dimensions {
    width: number;
    height: number;
}

/** A rectangle given by its top left coordinates and dimensions. */
export interface Box {
    /** The x coordinate of the the top left (xMin). */
    x: number;
    /** The y coordinate of the top left (yMin). */
    y: number;
    /** The width of the box. */
    width: number;
    /** The height of the box. */
    height: number;
}

/**
 * Extract the fileID of the {@link EnteFile} to which the face belongs from its
 * faceID.
 */
export const fileIDFromFaceID = (faceID: string) => {
    const fileID = parseInt(faceID.split("_")[0] ?? "");
    if (isNaN(fileID)) {
        assertionFailed(`Ignoring attempt to parse invalid faceID ${faceID}`);
        return undefined;
    }
    return fileID;
};

interface FaceDetection {
    box: Box;
    landmarks: Point[];
}

type FaceDirection = "left" | "right" | "straight";

export const faceDirection = ({ landmarks }: FaceDetection): FaceDirection => {
    const leftEye = landmarks[0]!;
    const rightEye = landmarks[1]!;
    const nose = landmarks[2]!;
    const leftMouth = landmarks[3]!;
    const rightMouth = landmarks[4]!;

    const eyeDistanceX = Math.abs(rightEye.x - leftEye.x);
    const eyeDistanceY = Math.abs(rightEye.y - leftEye.y);
    const mouthDistanceY = Math.abs(rightMouth.y - leftMouth.y);

    const faceIsUpright =
        Math.max(leftEye.y, rightEye.y) + 0.5 * eyeDistanceY < nose.y &&
        nose.y + 0.5 * mouthDistanceY < Math.min(leftMouth.y, rightMouth.y);

    const noseStickingOutLeft =
        nose.x < Math.min(leftEye.x, rightEye.x) &&
        nose.x < Math.min(leftMouth.x, rightMouth.x);

    const noseStickingOutRight =
        nose.x > Math.max(leftEye.x, rightEye.x) &&
        nose.x > Math.max(leftMouth.x, rightMouth.x);

    const noseCloseToLeftEye =
        Math.abs(nose.x - leftEye.x) < 0.2 * eyeDistanceX;
    const noseCloseToRightEye =
        Math.abs(nose.x - rightEye.x) < 0.2 * eyeDistanceX;

    if (noseStickingOutLeft || (faceIsUpright && noseCloseToLeftEye)) {
        return "left";
    } else if (noseStickingOutRight || (faceIsUpright && noseCloseToRightEye)) {
        return "right";
    }

    return "straight";
};
