[package]
name = "ente-wasm-lib"
edition = "2024"

[features]
contacts = [
    "dep:ente-contacts",
    "dep:serde",
    "dep:serde-wasm-bindgen",
    "dep:tsify",
    "dep:wasm-bindgen-futures",
]

[dependencies]
ente-contacts = { workspace = true, optional = true }
ente-core.workspace = true
js-sys.workspace = true
serde = { workspace = true, optional = true }
serde-wasm-bindgen = { workspace = true, optional = true }
thiserror.workspace = true
tsify = { workspace = true, optional = true }
wasm-bindgen.workspace = true
wasm-bindgen-futures = { workspace = true, optional = true }
