[package]
name = "ente-wasm-lib"
edition.workspace = true

[features]
accounts = ["dep:ente-accounts"]
collections = ["session", "dep:ente-collections"]
contacts = [
    "session",
    "dep:ente-contacts",
    "dep:wasm-bindgen-futures",
]
crypto = []
crypto-file = ["crypto", "dep:md-5"]
crypto-seal = ["crypto"]
locker = ["session", "dep:ente-locker"]
prelogin = ["accounts", "crypto"]
session = [
    "dep:ente-accounts",
    "dep:serde",
    "dep:serde-wasm-bindgen",
    "dep:tsify",
]

[dependencies]
ente-accounts = { workspace = true, optional = true }
ente-collections = { workspace = true, optional = true }
ente-contacts = { workspace = true, optional = true }
ente-core.workspace = true
ente-locker = { workspace = true, optional = true }
js-sys.workspace = true
log.workspace = true
md-5 = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde-wasm-bindgen = { workspace = true, optional = true }
thiserror.workspace = true
tsify = { workspace = true, optional = true }
wasm-bindgen.workspace = true
wasm-bindgen-futures = { workspace = true, optional = true }
web-sys = { version = "0.3.102", features = ["console"] }

[lints]
workspace = true
