[package]
name = "ente-frb-lib"
edition.workspace = true

[features]
contacts = ["dep:ente-contacts"]
legacy = ["dep:ente-legacy"]

[dependencies]
ente-contacts = { workspace = true, optional = true }
ente-core.workspace = true
ente-legacy = { workspace = true, optional = true }
flutter_rust_bridge.workspace = true

[lints]
workspace = true
