package api

import "github.com/gin-gonic/gin"

func Register(privateAPI, publicAPI gin.IRoutes, handlers *Handlers) {
	privateAPI.GET("/wall", handlers.ListWalls)
	privateAPI.POST("/wall", handlers.CreateWall)
	privateAPI.POST("/wall/profile", handlers.UpdateWallProfile)
	privateAPI.PUT("/wall/:wallID/slug", handlers.UpdateWallSlug)
	privateAPI.PATCH("/wall/:wallID/slug", handlers.UpdateWallSlug)
	privateAPI.POST("/wall/uploads/presign", handlers.PresignUpload)
	privateAPI.POST("/wall/posts", handlers.CreatePost)
	privateAPI.GET("/wall/feed", handlers.ListFeed)
	privateAPI.POST("/wall/posts/:postID/caption", handlers.UpdatePostCaption)
	privateAPI.PATCH("/wall/posts/:postID/caption", handlers.UpdatePostCaption)
	privateAPI.POST("/wall/posts/:postID/like", handlers.TogglePostLike)
	privateAPI.DELETE("/wall/posts/:postID", handlers.DeletePost)
	privateAPI.POST("/wall/posts/:postID/comments", handlers.CreateComment)
	privateAPI.DELETE("/wall/posts/:postID/comments/:commentID", handlers.DeleteComment)
	privateAPI.GET("/wall/community", handlers.Community)
	privateAPI.POST("/wall/follow/request", handlers.FollowRequest)
	privateAPI.GET("/wall/follow/requests", handlers.ListFollowRequests)
	privateAPI.GET("/wall/follow/requests/outgoing", handlers.ListOutgoingFollowRequests)
	privateAPI.POST("/wall/follow/request/cancel", handlers.CancelFollowRequest)
	privateAPI.POST("/wall/follow/approve", handlers.ApproveFollow)
	privateAPI.POST("/wall/follow/reject", handlers.RejectFollow)
	privateAPI.POST("/wall/follow/unfollow", handlers.Unfollow)
	privateAPI.GET("/wall/follow/followers", handlers.ListWallFollowers)
	privateAPI.POST("/wall/follow/shares/refresh", handlers.RefreshFollowShares)
	privateAPI.GET("/wall/follow/shares", handlers.ListFollowShares)
	privateAPI.POST("/wall/rotate", handlers.RotateWallKey)
	privateAPI.GET("/wall/links/:wallID", handlers.GetWallLink)
	privateAPI.POST("/wall/links", handlers.CreateWallLink)
	privateAPI.DELETE("/wall/links/:wallID", handlers.DeleteWallLink)

	publicAPI.GET("/wall/profile", handlers.GetWallProfile)
	publicAPI.GET("/wall/assets/redirect", handlers.AssetRedirect)
	publicAPI.GET("/wall/posts", handlers.ListPosts)
	publicAPI.GET("/wall/posts/:postID", handlers.GetPost)
	publicAPI.GET("/wall/posts/:postID/comments", handlers.ListComments)
	publicAPI.GET("/wall/versions", handlers.ListWallKeyVersions)
	publicAPI.GET("/wall/public/by-slug/:wallSlug", handlers.LookupWallBySlug)
	publicAPI.POST("/wall/links/session", handlers.WallLinkLogin)
}
