package api

import "github.com/gin-gonic/gin"

func Register(privateAPI, publicAPI gin.IRoutes, handlers *Handlers) {
	privateAPI.GET("/wall", handlers.ListWalls)
	privateAPI.POST("/wall", handlers.CreateWall)
	privateAPI.POST("/wall/profile", handlers.UpdateWallProfile)
	privateAPI.PUT("/wall/:wallID/slug", handlers.UpdateWallSlug)
	privateAPI.PATCH("/wall/:wallID/slug", handlers.UpdateWallSlug)
	privateAPI.POST("/wall/uploads/presign", handlers.PresignUpload)
	privateAPI.POST("/wall/posts", handlers.CreatePost)
	privateAPI.GET("/wall/feed", handlers.ListFeed)
	privateAPI.POST("/wall/posts/:postID/caption", handlers.UpdatePostCaption)
	privateAPI.PATCH("/wall/posts/:postID/caption", handlers.UpdatePostCaption)
	privateAPI.POST("/wall/posts/:postID/like", handlers.TogglePostLike)
	privateAPI.POST("/wall/posts/:postID/reply", handlers.ReplyToPost)
	privateAPI.DELETE("/wall/posts/:postID", handlers.DeletePost)
	privateAPI.GET("/wall/messages", handlers.ListMessages)
	privateAPI.GET("/wall/messages/:wallID", handlers.ListMessageThread)
	privateAPI.POST("/wall/messages/:wallID", handlers.CreateMessage)
	privateAPI.POST("/wall/message/:messageID/like", handlers.ToggleMessageLike)
	privateAPI.DELETE("/wall/message/:messageID", handlers.DeleteMessage)
	privateAPI.POST("/wall/friends/add", handlers.AddFriend)
	privateAPI.POST("/wall/friends/unfriend", handlers.Unfriend)
	privateAPI.GET("/wall/friends", handlers.ListWallFriends)
	privateAPI.GET("/wall/friends/relationship", handlers.FriendRelationship)
	privateAPI.POST("/wall/friends/shares/refresh", handlers.RefreshFriendShares)
	privateAPI.GET("/wall/friends/shares", handlers.ListFriendShares)
	privateAPI.POST("/wall/rotate", handlers.RotateWallKey)
	privateAPI.GET("/wall/links/:wallID", handlers.GetWallLink)
	privateAPI.POST("/wall/links", handlers.CreateWallLink)
	privateAPI.DELETE("/wall/links/:wallID", handlers.DeleteWallLink)

	publicAPI.GET("/wall/profile", handlers.GetWallProfile)
	publicAPI.GET("/wall/assets/redirect", handlers.AssetRedirect)
	publicAPI.GET("/wall/posts", handlers.ListPosts)
	publicAPI.GET("/wall/posts/:postID", handlers.GetPost)
	publicAPI.GET("/wall/posts/:postID/likes", handlers.ListPostLikers)
	publicAPI.GET("/wall/versions", handlers.ListWallKeyVersions)
	publicAPI.GET("/wall/public/by-slug/:wallSlug", handlers.LookupWallBySlug)
	publicAPI.GET("/wall/public/slug-availability/:wallSlug", handlers.WallSlugAvailability)
	publicAPI.POST("/wall/links/session", handlers.WallLinkLogin)
}
