[package]
name = "ente_rust"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
ente-accounts.workspace = true
ente-contacts.workspace = true
ente-core.workspace = true
flutter_rust_bridge.workspace = true

[features]
default = []
flutter = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
