# This is copied from Cargokit (which is the official way to use it currently)
# Details: https://fzyzcjy.github.io/flutter_rust_bridge/manual/integrate/builtin

include: package:lints/recommended.yaml

linter:
  rules:
    - prefer_relative_imports
    - directives_ordering
