[package]
name = "ente-cast-wasm"
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
ente-cast.workspace = true
ente-wasm-lib.workspace = true
serde.workspace = true
serde-wasm-bindgen.workspace = true
thiserror.workspace = true
tsify.workspace = true
wasm-bindgen.workspace = true

[lints]
workspace = true
