[package]
name = "ente-photos"
edition.workspace = true

[dependencies]
ente-assets.workspace = true
ente-collections.workspace = true
ente-core.workspace = true
ente-exif.workspace = true
ente-location.workspace = true
quick-xml.workspace = true
rusqlite = { workspace = true, default-features = true }
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
