[package]
name = "ente-accounts"
edition = "2024"

[features]
museum = []

[dependencies]
bip39 = { version = "2.0.0", default-features = false, features = ["std"] }
ente-core.workspace = true
getrandom.workspace = true
hex = "0.4.0"
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
srp.workspace = true
subtle.workspace = true
thiserror.workspace = true
urlencoding.workspace = true
uuid = { workspace = true, features = ["js", "serde", "v4"] }
zeroize.workspace = true

[dev-dependencies]
ente-test-support.workspace = true
hmac.workspace = true
mockito.workspace = true
sha1.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }
