name: "Lint (Apple)"

on:
    workflow_call:

permissions:
    contents: read

jobs:
    lint:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  persist-credentials: false
            - run: apple/scripts/lint.sh
