name: "Lint (Server)"

on:
    workflow_call:

permissions:
    contents: read

jobs:
    lint:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: server
        steps:
            - name: Checkout
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

            - name: Setup go
              uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
              with:
                  go-version-file: server/go.mod
                  cache-dependency-path: server/go.sum
                  cache: true

            - name: Lint
              run: ./scripts/lint.sh

            - name: Test
              run: ./scripts/test-with-postgres.sh docker
