name: "Deploy (2of3)"

on:
    workflow_dispatch:

permissions:
    contents: read

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: production

        defaults:
            run:
                working-directory: web

        steps:
            - name: Checkout
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

            - name: Setup node
              uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
              with:
                  node-version: 24
                  cache: "npm"
                  cache-dependency-path: "web/package-lock.json"

            - name: Install dependencies
              run: npm ci

            - name: Audit dependencies
              run: npm audit --audit-level critical

            - name: Build 2of3
              run: npm run build:twoof3

            - name: Publish 2of3
              uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
              with:
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  command: pages deploy --project-name=ente --commit-dirty=true --branch=deploy/2of3 web/apps/twoof3/out
